### ISSUE TITLE
Thoughts on layout improvements and going further

### ISSUE THREAD

**Issue by ghost** [Abiy-T/CMSC495-Hotel_Reservation_Project#1]
Layout
* Should be responsive&mdash;the scene doesn't resize with the window/stage right now. I'm not familiar with jfx, but it looks like using `AnchorPane` at the top level is part of the issue.
* I think there should only be 3 tabs, it should help minimize error handling
  1. Home screen
  2. A `StackPane` of reserve, pay, and confirm (shows room number) pages
  3. A `StackPane` of login and logout pages

Implementing the controller
* Tab 2 disabled by default, enabled on login.
* Reserve page
  * Room types/number of guests combo boxes disabled by default.
  * An event listener on both `DatePicker`  that looks like
    ```
    if checkIn or checkOut are not picked
        return
    if checkIn >= checkOut 
        disable combo boxes
    else 
        query room availability and store results
        enable/update combo boxes
    ```
     Listeners could then be added to both combo boxes to change each other based on the room query results. If they are set up right, the reservation should be valid to submit based on whether they are enabled and have values.
  * Also amenities could be changed to a row of multi-select check boxes.
* Payment page
  * Input validation here should probably just stay basic; null checks, maybe a ccard format check?

Let me know what you guys think.

**Comment by Abiy-T** [comment]
@alexdwivedi 
- Layout
 	I will make the scene to Auto resize or fit to standard Window. 
        For Tabs your saying we should Combine reservation & Payment page together? 

-  Implementing  the controller 
   I agree with your suggestions i was thinking about to add An event Listener to DatePicker and change  
 Amenities to Radio buttons.

**Comment by ghost** [comment]
Yes, the payment page only needs to be shown after reservation submission, and it will have info specific to that submission (res no. and total amount). 

For correctness, the group of amenity radios should probably be in their own scroll area since they will be loaded dynamically. What if there are 100 amenities in the database? That is a bit extra though, 4 slots is probably fine.
